;; This "home-environment" file can be passed to 'guix home reconfigure'
;; to reproduce the content of your profile.  This is "symbolic": it only
;; specifies package names.  To reproduce the exact same profile, you also
;; need to capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(use-modules (gnu home)
             (gnu packages)
             (gnu services)
             (guix gexp)
             (gnu home services shells)
			       (gnu home services gnupg)
             (gnu packages gnupg))

(home-environment
  ;; Below is the list of packages that will show up in your
  ;; Home profile, under ~/.guix-home/profile.
  (packages (specifications->packages (list "swaylock"
                                            "swayidle"
                                            "mupdf"
                                            "imagemagick"
                                            "libheif"
                                            "stapler"
                                            "bc"
                                            "lemonbar"
                                            "icedove-wayland"
                                            "ffmpeg"
                                            "gammastep"
                                            "tlpui"
                                            "usbmuxd"
                                            "libimobiledevice"
                                            "blueman"
                                            "bluez"
                                            "bluez-qt"
                                            "grimshot"
                                            "cppcheck"
                                            "xdot"
                                            "xournalpp"
                                            "nomacs"
                                            "grim"
                                            "dotnet"
                                            "python"
                                            "aspell"
                                            "hunspell"
                                            "libvterm"
                                            "libtool"
                                            "cmake"
                                            "ghostscript"
                                            "tesseract-ocr"
                                            "wireplumber"
                                            "git-filter-repo"
                                            "pipewire"
                                            "i3-autotiling"
                                            "flatpak-xdg-utils"
                                            "xdg-desktop-portal-wlr"
                                            "xdg-desktop-portal"
                                            "shotcut"
                                            "obs-vkcapture"
                                            "obs-wlrobs"
                                            "obs"
                                            "winetricks"
                                            "wine"
                                            "dbus"
                                            "xset"
                                            "gnome"
                                            "gocryptfs"
                                            "qdirstat"
                                            "sdl2"
                                            "libpng"
                                            "automake"
                                            "autoconf"
                                            "wl-clipboard"
                                            "wtype"
                                            "fontforge"
                                            "gtk"
                                            "fcitx5-gtk4"
                                            "fcitx5-chinese-addons:gui"
                                            "fcitx5-gtk:gtk3"
                                            "fcitx5-gtk:gtk2"
                                            "emacs-straight-el"
                                            "anki"
                                            "node"
                                            "brillo"
                                            "clipman"
                                            "wlogout"
                                            "dunst"
                                            "playerctl"
                                            "pulsemixer"
                                            "ponymix"
                                            "dex"
                                            "emacs-next-pgtk"
                                            "python-pip"
                                            "epiphany"
                                            "fcitx5"
                                            "fcitx5-chinese-addons"
                                            "fcitx5-configtool"
                                            "fcitx5-qt"
                                            "fcitx5-gtk"
                                            "fcitx5-rime"
                                            "zoom"
                                            "libreoffice"
                                            "nautilus"
                                            "pavucontrol"
                                            "zathura-pdf-mupdf"
                                            "zathura"
                                            "trash-cli"
                                            "tessen"
                                            "rofi-wayland"
                                            "git-lfs"
                                            "waybar"
                                            "ungoogled-chromium"
                                            "krita"
                                            "gnome-tweaks"
                                            "flatpak"
                                            "gnome-console"
                                            "emacs-magit"
                                            "pinentry"
                                            "password-store"
                                            "xdg-utils"
                                            "firefox"
                                            "mpv"
                                            "qbittorrent"
                                            "icecat"
                                            "texlive"
                                            "vscodium"
                                            "kitty"
                                            "gnome-shell-extensions"
                                            "anytype"
                                            "git"
                                            "sway"
                                            "curl"
                                            "xclip"
                                            "setxkbmap"
                                            "xkbutils"
                                            "alacritty"
                                            "icedtea"
                                            "openjdk"
                                            "pass-otp"
                                            "prismlauncher"
                                            "bat"
                                            "btop"
                                            "libfido2"
                                            "pam-u2f"
                                            "qpdf"
                                            "librime"
                                            "iwd"
                                            "hwinfo"
                                            "acpi"
                                            "jq"
                                            "swayr"
                                            "zoxide"
                                            "lf"
                                            "fd"
                                            "ripgrep"
                                            "rust"
                                            "gcc-toolchain"
                                            "opendoas"
                                            "rust-cargo"
                                            "perl-file-mimeinfo"
                                            "file"
                                            "bash"
                                            "ncurses"
                                            "perl"
                                            "fzf"
                                            "zsh"
                                            "go"
                                            "neovim"
                                            "pandoc"
                                            "thinkfan"
                                            "vim"
                                            "make"
                                            "htop"
                                            "shellcheck"
                                            "neofetch"
                                            "check"
                                            "flameshot"
                                            "tomb"
                                            "egl-wayland"
                                            "ninja"
                                            "meson"
                                            "recutils"
                                            "brightnessctl"
                                            "font-awesome"
                                            "gcc-toolchain:static"
                                            "patchelf"
                                            "glibc"
                                            "aspell-dict-en"
                                            "hunspell-dict-en-us"
                                            "font-fira-code"
                                            "font-ibm-plex"
                                            "font-google-noto-emoji"
                                            "rime-data"
                                            "zsh-autosuggestions"
                                            "fcitx5-material-color-theme"
                                            "zsh-syntax-highlighting"
                                            "zsh-autopair"
                                            "zsh-completions"
                                            "font-iosevka"
                                            "font-google-noto-sans-cjk"
                                            "font-google-noto-serif-cjk"
                                            "font-microsoft-web-core-fonts"
                                            "gnome-shell-extension-vitals")))

  ;; Below is the list of Home services.  To search for available
  ;; services, run 'guix home search KEYWORD' in a terminal.
  (services
   (list
    (service home-gpg-agent-service-type
             (home-gpg-agent-configuration
              (pinentry-program
               (file-append pinentry-gtk2 "/bin/pinentry-gtk2"))
              (ssh-support? #t)))
    (service home-zsh-service-type
             (home-zsh-configuration
              (zshrc (list (local-file "/home/ben/src/guix-config/.zshrc" "zshrc")))
              (zshenv (list (local-file "/home/ben/src/guix-config/.zshenv" "zshenv")))
              (zprofile (list (local-file "/home/ben/src/guix-config/.zprofile" "zprofile"))))))))
